name: Clone Two Repositories

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'
        type: string

jobs:
  clone-repos:
    runs-on: ubuntu-latest

    steps:
    - name: Clone first repository
      uses: actions/checkout@v4
      with:
        repository: mcas101/delder_bot
        path: ./delder_bot
        token: ${{ secrets.PAT_TOKEN }}

    - name: Clone second repository
      uses: actions/checkout@v4
      with:
        repository: mcas101/music
        path: ./music
        token: ${{ secrets.PAT_TOKEN }}

    - name: Clone external repo
      uses: actions/checkout@v4
      with:
        repository: marco-polo-org/tf-gh-actions-rnd
        path: ./tf-gh-actions-rnd
        token: ${{ secrets.PAT_TOKEN}}

    - name: List cloned repositories
      run: |
        echo "Contents of workspace:"
        ls -la
        echo "\nContents of first repo:"
        ls -la delder_bot
        echo "\nContents of second repo:"
        ls -la music
        echo "\nContents of external repo:"
        ls -ls tf-gh-actions-rnd
        
