name: DynamoDB Local Test

on:
  workflow_dispatch:
    inputs:
      retries:
        description: 'Number of retries'
        required: false
        default: '60'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Start DynamoDB Local
        run: |
          docker run -d -p 8000:8000 amazon/dynamodb-local
          # Wait for container to start
          sleep 5
          docker ps

      - name: Docker container debug info
        run: |
          docker ps -a
          docker logs $(docker ps -aq --filter name=dynamodb)

      - name: Create wait script
        run: |
          cat > wait_for_success.sh << 'EOF'
          #!/bin/bash
          
          function main {
              local retries=${RETRIES:-60}

              until [[ ${retries} -eq 0 ]]; do
                  if "$@"; then
                      echo "ready"
                      exit 0
                  else
                      echo "not ready, pausing 1s"
                      (( retries-=1 ))
                      sleep 1
                  fi
              done

              echo "Retries exceeded!  Unable to connect to service."
              exit 1
          }

          main "$@"
          EOF
          chmod +x wait_for_success.sh

      - name: Set up AWS credentials
        env:
          AWS_ACCESS_KEY_ID: dummy
          AWS_SECRET_ACCESS_KEY: dummy
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_DEFAULT_REGION

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Wait for DynamoDB
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8000 > /dev/null; then
              echo "DynamoDB is running"
              break
            fi
            echo "Waiting for DynamoDB... attempt $i"
            sleep 2
          done

      - name: Create test table with retries
        env:
          RETRIES: ${{ inputs.retries }}
        run: |
          ./wait_for_success.sh aws dynamodb create-table \
          --endpoint-url http://localhost:8000 \
          --table-name service-test-call-correlation \
          --attribute-definitions \
            AttributeName=correlationId,AttributeType=S \
            AttributeName=startUtc,AttributeType=N \
          --key-schema \
            AttributeName=correlationId,KeyType=HASH \
            AttributeName=startUtc,KeyType=RANGE \
          --region us-east-1 \
          --provisioned-throughput \
            ReadCapacityUnits=10,WriteCapacityUnits=10 \
          && echo "Table created"

      - name: Verify table creation
        run: |
          aws dynamodb describe-table \
            --table-name service-test-call-correlation \
            --endpoint-url http://localhost:8000
